;; -*- lexical-binding: t; -*-
(use-package emacs
  :ensure nil
  :custom
  (auto-save-default nil)
  (backup-directory-alist (list (cons "." (locate-user-emacs-file "backups/"))))
  (blink-cursor-mode nil)
  (bookmark-save-flag 1)
  (bookmark-fringe-mark nil)
  (column-number-mode t)
  (confirm-kill-processes nil)
  (create-lockfiles nil)
  (css-indent-offset 2)
  (deactivate-mark nil)
  (delete-selection-mode t)
  (enable-recursive-minibuffers t)
  (frame-title-format "%b")
  (fill-column 80)
  (help-window-select t)
  (indent-tabs-mode nil)
  (indicate-empty-lines t)
  (inhibit-startup-screen t)
  (kill-whole-line t)
  (make-backup-files nil)
  (mouse-autoselect-window t)
  (native-comp-async-report-warnings-errors nil)
  (read-hide-char ?\u2022)   ; BULLET
  (repeat-mode t)
  (ring-bell-function #'ignore)
  (safe-local-variable-directories '("~/.emacs.d"))
  (savehist-mode t)
  (save-place-mode t)
  (sh-basic-offset 2)
  (trusted-content '("~/.emacs.d/" "/var/home/lina/.emacs.d/"))
  (use-dialog-box nil)
  (use-short-answers t)
  (vc-handled-backends nil)
  (warning-minimum-level :error)
  :config
  (dolist (key '("M-u" "s-q" "<XF86Back>" "<XF86Forward>"))
    (unbind-key key global-map))
  (set-scroll-bar-mode 'right)
  :hook (after-init . (lambda ()
                        (ignore-errors
                          (make-directory (locate-user-emacs-file "backups/")))))
  :bind
  (("C-k" . kill-whole-line)
   ("C-v" . yank)
   ("C-z" . undo)
   ("M-;" . comment-line)
   ("M-i" . completion-at-point)
   ("M-," . pop-to-mark-command)
   ("C-," . pop-global-mark)
   ("C-f" . find-file)
   ("C-x C-g" . keyboard-quit)
   ("C-x C-x" . revert-buffer-quick)
   ("C-x C-c" . delete-frame-or-kill-emacs)
   ("C-w" . c-w-dwim)
   ("C-x 2" . split-and-follow-vertically)
   ("C-x 3" . split-and-follow-horizontally)
   ("M-<left>" . backward-word)
   ("M-<right>" . forward-word)
   ("C-<right>" . forward-sexp)
   ("C-<left>" . backward-sexp)
   (:map minibuffer-local-map
         ("C-u" . backward-kill-sentence))))
